ApeWorX/ape-vyper

- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/contracts/failing_contracts/contract_undeclared_variable.vy
- tests/contracts/failing_contracts/contract_unknown_pragma.vy
- tests/contracts/passing_contracts/contract.vy
- tests/test_integration.py
fixes: #26
Follow advice from @fubuloubu 
1. Raise compiler-centric error in the compile phase that actually preserves the std-err data OR uses the natural exception in the error output.
2. Other error improvements.
Make sure you can see the compile related errors in bad vyper code, e.g.:
```
ERROR: (VyperCompileError) vyper.exceptions.StructureException: Unsupported syntax for module namespace: Expr
contract "/var/folders/hg/17b1zhsn1n3d8b4rgh6ntt_w0000gn/T/vyper-ajp3wgog.vy", line 1:0
---> 1 asdfasdfasdf
-------^
2
[15687] Failed to execute script vyper_compile
```
^ Not exactly sure where the `[15687] Failed to execute script vyper_compile` comes from though
Also, make sure good vyper good still compiles!
> fix: preserve compiler error

- ape_vyper/compiler.py
- pyproject.toml
- setup.py
Requires release of https://github.com/ApeWorX/ape/pull/408
Correct all validation errors from ethpm-types! Fixes paths in the package manifest to use a base path of the project's `contracts/` directory.
set the base path in the compiler as well as read the bytes assuming such base path.
Because we don't have access to the `ProjectManager` here (to get the `contracts/` directory path), I just made a config property for the base path.
Make sure using this plus PR 408 in ape core that you can compile contracts and that your source IDs are paths.
> fix: adhere to correct ethpm-types

- ape_vyper/compiler.py
Fix bug preventing local install of `vyper` package from working.
Two things had to be done:
1. Checks to make sure we **don't** attempt to download the package if we detect we are using the version we have in our site-packages. (detected using the pragma spec).
2. Specify the path to the binary. This is needed so we can still use the `vvm` method.
Two cases needed for testing (that I have tried myself too):
Case 1:
1. Install `vyper` from source (either a local clone or via `git`)
2. Compile a contract using the _next_ bumped version. Right now, the latest tag on `vyper` is `0.3.1`, so set your pragma to `0.3.2`. It should work now!
Case 2 (regression test):
1. Make sure you **do not** have vyper installed locally.
2. Specify a pragma from a released tag, such as `0.3.1`.
3. Notice you …
> fix: allow source install of vyper

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- ape_vyper/compiler.py
- pyproject.toml
- setup.py
* Add python 3.10 support now that vyper-lang is able to support it
> chore: support python 3.10

- CONTRIBUTING.md
- tests/conftest.py
Separated the test suite's vvm installations from the user's, which also ensures the tests
start from a clean slate on each run
fixes: #49 
Added a session scoped, auto-used pytest fixture for setting the install path at startup and cleaning it up at teardown
Clean out your `~/.vvm` directory, run the tests, and verify that no Vyper installations are there after the suite completes.
Also should note starting up the test suite may take a tiny bit longer just because it's now downloading the Vyper binaries when it needs them, rather than relying on the real installations that may be present.
> test: use auto-generated vvm install path

- ape_vyper/compiler.py
This corresponds with https://github.com/ApeWorX/ethpm-types/pull/47 to ensure we have `ContractType.sourcemap` and `ContractType.pcmap` available when compiling Vyper contracts
> feat: add source map to contract type output

- ape_vyper/compiler.py
- setup.py
- tests/contracts/passing_contracts/contract_with_dev_messages.vy
- tests/test_compiler.py
fixes: APE-308
Requires https://github.com/ApeWorX/ethpm-types/pull/51
Facilitates https://github.com/ApeWorX/ape/pull/1125
During the `compile()` step we parse the source line-by-line and save the line number + message if we encounter a dev message (`#dev: foobar`)
Via `test_compile_parse_dev_messages()` and the new `contract_with_dev_messages.vy` test contract.
> feat: add ContractType.dev_messages support

- .gitignore
- .pre-commit-config.yaml
- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/DirectoryWithExtension.vy/README.md
- tests/contracts/passing_contracts/contract.vy
- tests/contracts/passing_contracts/contract_with_dev_messages.vy
- tests/test_compiler.py
Following suit with https://github.com/ApeWorX/ape/pull/1147/files and https://github.com/ApeWorX/ape-solidity/pull/82 but no bug here, only ensuring it works via adding new tests as well updating from template
> test: ensure can have directory with `.vy` in the name

- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- tests/contracts/passing_contracts/use_iface.vy
- tests/contracts/passing_contracts/use_iface2.vy
- tests/test_compiler.py
fixes: #43 
Fixes: APE-406
This is needed for Etherscan verification and I think also helps Ape core compile Vyper projects (IICR why we did it in `ape-solidity`).
This is step 1 to getting Verification working for Vyper contracts.
> feat: implement `get_imports()` API method

- setup.py
this should cause it to use the right version by default
fixes: APE-569
> chore: remove pin on cz so it works better

- .github/workflows/commitlint.yaml
- .gitignore
- .pre-commit-config.yaml
- README.md
- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/.build/__local__.json
- tests/ExampleDependency/contracts/Dependency.vy
- tests/ape-config.yaml
- tests/contracts/passing_contracts/interfaces/IFace2.vy
- tests/contracts/passing_contracts/use_iface.vy
- tests/test_compiler.py
also refactored to using `vvm.compile_standard` mode
fixes: #37
fixes: #38
fixes: #62 
Fixes: APE-412
Fixes: APE-656
> feat: support interfaces

- ape_vyper/compiler.py
- setup.py
- tests/contracts/passing_contracts/contract.vy
- tests/test_compiler.py
* Realized can make the PC Map from the output AST JSON.
* This allows removing `asttokens` as a dependency which increases compatibility with out languages written in Python (old-school Cairo)
* Also begins to form an idea on how to use this AST JSON... I am soliciting ideas on how we can include this in `ethpm-types` for generating an overall coverage profile. There are different node types between Vyper and Solidity, so have to keep it relatively generic. 
* Adds `ast` to `ContractType`
Mostly in this PR https://github.com/ApeWorX/ethpm-types/pull/61
* Things still work
* Now have AST data structure in ContractTypes that we can use for accurate Coverage profiles
> refactor: utilize AST map to derive PC Map [APE-670]

- .github/workflows/commitlint.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/test.yaml
- ape_vyper/compiler.py
- setup.py
- tests/contracts/passing_contracts/contract.vy
- tests/test_compiler.py
fixed issue where immutable member access in functions would throw off the PCMap
> fix: issue with immutable member access in PCMap calculation [APE-909]

- .github/workflows/test.yaml
- ape_vyper/compiler.py
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/interfaces/IRegistry.vy
- tests/contracts/passing_contracts/registry.vy
- tests/contracts/passing_contracts/traceback_contract.vy
- tests/test_compiler.py
Implements necessary API methods for performing traceback line showings as well as coverage.
Implementation borrowed from Brownie somewhat, but basically track the trace while mapping PC to known locations, including both from the source code as well as from the error map.
Use this PR from ape core: https://github.com/ApeWorX/ape/pull/1337 and cause uncaught contract logic errors to happen of any kind.
Observe them in the traceback.
> feat: `trace_source` implementation [APE-754]

- README.md
- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/contract.vy
- tests/contracts/passing_contracts/contract_with_dev_messages.vy
- tests/contracts/passing_contracts/interfaces/IRegistry_039.vy
- tests/contracts/passing_contracts/non_payable_default.vy
- tests/contracts/passing_contracts/payable_default.vy
- tests/contracts/passing_contracts/registry_039.vy
- tests/contracts/passing_contracts/traceback_contract_039.vy
- tests/test_compiler.py
Fixes: APE-1007
* adds fallback error check to pcmap
* makes sure it works
* make sure you can traces from __default__ (fallback)
> feat: __default__ not implemented error [APE-1007]

- ape_vyper/exceptions.py
- tests/test_compiler.py
when failing to compile a vyper file, show the formatted message.
this will include line numbers whenever applicable!
fixes: #71 
errors looks like this now:
```
UndeclaredDefinition:'hello' has not been declared
contract "contract_undeclared_variable.vy", function "foo1", line 5:4 
4 def foo1() -> bool:
---> 5     hello = world
-----------^
6     return True
```
notice the line nos
use `formattedMessage` instead of `message` when it is present.
take a contract like this:
```
@external
def foo1() -> bool:
hello = world
return True
```
try to compile it:
```sh
ape compile
```
you should see an error like this now:
```
ERROR: (VyperCompileError) und.vy
UndeclaredDefinition:'hello' has not been declared. 
contract "und.vy:5", function "foo1", line 5:4 
4 def foo1() -> bool:
---> 5     hello …
```
> fix: show line numbers on compiler fail [APE-731]

- ape_vyper/compiler.py
- tests/test_compiler.py
Issue prevent ing empty contracts from compiling
an early return in PCMap generation
compile an empty file with a `.vy` suffix
> fix: empty contract [APE-1129]

- README.md
- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/contract_with_dev_messages.vy
- tests/contracts/passing_contracts/optimize_codesize.vy
- tests/contracts/passing_contracts/pragma_with_space.vy
- tests/test_ape_reverts.py
- tests/test_compiler.py
fixes: #96 APE-1462
Compile each set of contracts separately according to specified optimization level in pragmas.
If no optimization level is there, we fall back to "True" as before.
also, for version pragmas, we support the new format now, looks like `#pragma version 0.3.10`
Compile any contract with `#pragma optimize codesize`
> feat: Support Vyper 0.3.10

- .pre-commit-config.yaml
- README.md
- ape_vyper/compiler.py
- setup.py
- tests/conftest.py
- tests/projects/version_in_config/ape-config.yaml
- tests/projects/version_in_config/contracts/v_contract.vy
- tests/test_compiler.py
same as https://github.com/ApeWorX/ape-solidity/pull/46
> feat: allow specifying version in config [APE-1473]

- README.md
Add notes to readme about setting evm version, via config and via pragma
~~- [ ] New test cases have been added and are passing~~
> docs: add notes about evm version config to readme [APE-1592]

- README.md
- ape_vyper/_cli.py
- ape_vyper/ast.py
- ape_vyper/compiler.py
- ape_vyper/interface.py
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/flatten_me.vy
- tests/test_cli.py
- tests/test_compiler.py
Adds Vyper contract flattener functionality.
fixes: #75
> feat: contract flattener

- .github/workflows/codeql.yml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- ape_vyper/_cli.py
- ape_vyper/ast.py
- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- ape_vyper/interface.py
- pyproject.toml
- setup.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/contracts/passing_contracts/flatten_me.vy
- tests/contracts/passing_contracts/use_iface.vy
- tests/projects/coverage_project/ape-config.yaml
- tests/test_cli.py
- tests/test_compiler.py
- tests/test_coverage.py
> refactor!: 0.8 changes

- ape_vyper/__init__.py
- ape_vyper/_utils.py
- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/interfaces/IFaceZeroFour.vyi
- tests/contracts/passing_contracts/zero_four.vy
- tests/contracts/passing_contracts/zero_four_module.vy
- tests/test_compiler.py
Make it so can compile on 0.4.0
Had to use absolute paths.
> feat: vyper 0.4 support

- ape_vyper/compiler.py
- tests/conftest.py
- tests/contracts/passing_contracts/flatten_me.vy
- tests/contracts/passing_contracts/subdir/zero_four_in_subdir.vy
- tests/contracts/passing_contracts/use_iface.vy
- tests/contracts/passing_contracts/use_iface2.vy
- tests/contracts/passing_contracts/zero_four.vy
- tests/contracts/templates/reverts.template
- tests/contracts/templates/traceback_contract.template
- tests/test_cli.py
- tests/test_compiler.py
fixes: issue where couldn't import from root of project in non-relative manner
fixes: issue with ethereum builtin namespace imports
> fix: issues with 0.4 imports

- ape_vyper/compiler.py
- ape_vyper/interface.py
- setup.py
- tests/contracts/passing_contracts/zero_four.vy
- tests/contracts/passing_contracts/zero_four_module.vy
- tests/contracts/passing_contracts/zero_four_module_2.vy
- tests/test_cli.py
- tests/test_compiler.py
Adds the ability to flatten vyper 0.4 contracts via bumping vyper and handling module-imports
> feat: Vyper 0.4 flattener

- .pre-commit-config.yaml
- ape_vyper/compiler.py
- setup.py
- tests/contracts/passing_contracts/zero_four_snekmate_erc20.vy
- tests/test_compiler.py
fixes: #125 
implicit relative imports from the same directory as the source were not working
> fix: handle implicit relative imports

- ape_vyper/compiler.py
- tests/test_compiler.py
compile_code was not using the temp project, and thus creating a file locally that never got cleaned up.
this pr:
1. actually uses the temp project (main issue fix)
2. cleans up file anyways, just in case!
3. fixes a failing test (not a bug just the setup needed adjusting)
also if you are reviewing this PR, please also review this one: https://github.com/ApeWorX/ape-vyper/pull/130 which is important
> fix: issue where `compile_code` was creating a file

- .pre-commit-config.yaml
- ape_vyper/compiler.py
- setup.py
- tests/ape-config.yaml
- tests/test_compiler.py
Using dependencies like snekmate for Vyper 0.4 was annoying because Vyper 0.3 range dependencies required being compiled for their abis but not in 0.4 so it is a difficult balance.
This PR compiles ABI-based dependencies at a more apt time, when we are further aware that they are indeed ABI-based dependencies and not site-package based or something else.
move stuff around
Use snekmate via config like this:
```yaml
dependencies:
- python: snekmate
config_override:
contracts_folder: .
```
Use something in the Token.vy like @Ninjagod1251 did.
compile
```sh
ape compile
```
Should not see warning anymore.
Also it compiles much faster and is cleaner
> fix: compile ABI-based dependencies at better time

- README.md
- ape-config.yaml
- ape_vyper/compiler/_versions/base.py
- ape_vyper/compiler/_versions/vyper_04.py
- ape_vyper/compiler/api.py
- ape_vyper/config.py
- ape_vyper/flattener.py
- ape_vyper/imports.py
- ape_vyper/traceback.py
- tests/conftest.py
- tests/contracts/passing_contracts/subdir/zero_four_in_subdir.vy
- tests/contracts/passing_contracts/use_iface.vy
- tests/functional/test_compiler.py
to use decimals in Vyper 0.4, you must add the setting `enable_decimals`.
Add the setting for vyper-json
```yaml
vyper:
enable_decimals: true
```
> feat: add support for `enable_decimals` for Vyper 0.4

- .pre-commit-config.yaml
- ape_vyper/__init__.py
- ape_vyper/_cli.py
- ape_vyper/_utils.py
- ape_vyper/compiler/_versions/base.py
- ape_vyper/compiler/_versions/vyper_02.py
- ape_vyper/compiler/_versions/vyper_04.py
- ape_vyper/compiler/api.py
- ape_vyper/coverage.py
- ape_vyper/flattener.py
- ape_vyper/imports.py
- ape_vyper/interface.py
- ape_vyper/traceback.py
- setup.cfg
- setup.py
make any lengthy imports happens in a local ctx so `ape --help` isnt slowed down by this
> chore: lazify CLI loading

- .github/workflows/test.yaml
- ape-config.yaml
- ape_vyper/_utils.py
- ape_vyper/compiler/_versions/base.py
- ape_vyper/compiler/_versions/utils.py
- ape_vyper/compiler/_versions/vyper_04.py
- ape_vyper/compiler/api.py
- ape_vyper/config.py
- ape_vyper/exceptions.py
- ape_vyper/imports.py
- setup.cfg
> refactor: use vyper instead of vyper JSON for 0.4

- ape_vyper/_cli.py
- setup.cfg
- tests/functional/test_cli.py
> feat: install vyper CLI using CLI

- README.md
- ape_vyper/_cli.py
- tests/functional/test_cli.py
```
ape vyper vvm list --available
```
> feat: list available vyper versions CLI

- ape_vyper/ast.py
- ape_vyper/compiler/_versions/vyper_04.py
- pyproject.toml
- tests/conftest.py
- tests/functional/test_compiler.py
Noticed we were using `settings` and not `settings_set` to pull the decimals kwarg from the settings profile
fixes: #152
~~- [ ] Documentation has been updated~~
> fix(config): enable decimals for Vyper 0.4
