- setup.py
> fix: install tqdm so downloading binaries works in vvm

- .github/release-drafter.yml
- .github/workflows/draft.yaml
note: won't work until after it's merged
> chore: add `release-drafter`

- ape_vyper/compiler.py
- setup.py
> attemping to fix https://github.com/ApeWorX/ape-vyper/issues/13

- ape_vyper/compiler.py
- tests/contracts/contract_no_pragma.vy
- tests/test_integration.py
fixed as per https://github.com/ApeWorX/ape-vyper/issues/17#issuecomment-876689353 & tested working locally
> fix: self.installed_versions is not being handled properly

- README.md
- ape_vyper/compiler.py
- setup.py
- tests/contracts/failing_contracts/contract_with_error.vy
- tests/contracts/passing_contracts/contract.vy
- tests/contracts/passing_contracts/contract_no_pragma.vy
> chore: upgrade to latest ape

- README.md
- setup.py
> chore: prepare for beta

- ape_vyper/compiler.py
Depends on `eth-ape` v0.1.0b5 release (including `ethpm-types` breaking changes)
> fix: update for breaking changes in ethpm-types

- setup.py
> fix: eth-ape version

- setup.py
> feat: upgrade vyper

- CONTRIBUTING.md
- README.md
- setup.py
> chore: bump ape to 0.4

- setup.py
> chore: bump [APE-687]

- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- tests/contracts/passing_contracts/erc20.vy
- tests/test_compiler.py
fixes: #https://github.com/ApeWorX/ape/issues/1398
finally was able to repro and discovered that this fixes it
> fix: index error from vyper 3.8 and non-payable PC detection [APE-885]

- .github/workflows/commitlint.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
There is a very strange dependency happening. It happened on one of the merges to main and it also happened on publish.
I can't get it to happen locally, so not sure.
> fix: ci attempt fix [APE-917]

- .github/workflows/test.yaml
- README.md
- pyproject.toml
- setup.py
- tests/test_compiler.py
> feat: python3.11 support [APE-1039]

- ape_vyper/compiler.py
- ape_vyper/exceptions.py
- setup.py
- tests/conftest.py
- tests/test_ape_reverts.py
- tests/test_compiler.py
> feat: 0.3.10rc3 support and refactor to packaging.SpecifierSet [APE-1390]

- ape_vyper/compiler.py
- tests/test_compiler.py
implements new API from https://github.com/ApeWorX/ape/pull/1707
> feat: compile code implementation [APE-1478]

- ape_vyper/compiler.py
- setup.py
- tests/conftest.py
- tests/projects/coverage_project/ape-config.yaml
- tests/test_compiler.py
use with https://github.com/ApeWorX/ape/pull/1705
> feat: use settings and upgrade ape [APE-1477]

- .pre-commit-config.yaml
- ape_vyper/compiler.py
- setup.py
- tests/contracts/passing_contracts/evm_pragma.vy
- tests/test_compiler.py
> feat!: Ape 0.7 upgrade [APE-1603]

- .github/workflows/commitlint.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .mdformat.toml
- .pre-commit-config.yaml
- pyproject.toml
- setup.py
doing this to make PR for vyper 0.4.0 support smaller
> chore: lint updates

- .github/workflows/codeql.yml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- ape_vyper/compiler.py
- pyproject.toml
- setup.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/test_cli.py
- tests/test_compiler.py
- tests/test_coverage.py
feat: add support for Python 3.12
chore: update lint dependencies
fixes: #
> feat: python 3.12

- .pre-commit-config.yaml
- ape_vyper/compiler.py
- tests/ape-config.yaml
- tests/conftest.py
- tests/contracts/passing_contracts/flatten_me.vy
- tests/contracts/passing_contracts/use_iface.vy
- tests/test_compiler.py
targeting the feat/08 branch with the project refactor changes
> feat!: project refactor

- .github/workflows/test.yaml
- .pre-commit-config.yaml
- README.md
- ape_vyper/compiler.py
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/contracts/passing_contracts/interfaces/IFaceZeroFour.vyi
- tests/contracts/passing_contracts/zero_four.vy
- tests/contracts/passing_contracts/zero_four_module.vy
- tests/test_ape_reverts.py
- tests/test_compiler.py
fixes: #119
requires https://github.com/ApeWorX/ape/pull/2163
> fix: handle python-based imports in Vyper contracts

- .github/workflows/test.yaml
- pyproject.toml
token wasnt being set, causing CI failures from the timeouts
> test: properly set GH access token

- .pre-commit-config.yaml
- README.md
- ape_vyper/__init__.py
- ape_vyper/compiler/api.py
- setup.py
> chore: realizations from performance and lint upgrades

- setup.py
> fix: wider pin on VVM

- README.md
- ape_vyper/compiler/_versions/base.py
- ape_vyper/compiler/_versions/vyper_04.py
- tests/functional/test_compiler.py
you can now specify the output formats you want
> feat: allow customizing and configuring which output formats you want

- ape_vyper/config.py
fixes: #
~~- [ ] Documentation has been updated~~
> fix: typing error in Remapping model
